### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by revilowaldow** [Pf2eTools/homebrew#2]
Is it worth directing this to `https://raw.githubusercontent.com/Pf2eToolsOrg/Pf2eTools/master/test/schema-template/schema.json` instead of a local schema file so it's always up to date. In time we can have the build part of the schema build two directories, the site and the brew version directly in the site code and we can reposition this then.

https://github.com/Pf2eToolsOrg/homebrew/blob/e4fddb3cde2a091ed44c097900e69a5fad8e3015/_test/test-json.js#L13

**Comment by MrVauxs** [comment]
Future Note: Not possible yet until AJV allows using URLs in schema validation.
Alternatively, we add PF2eTools as a submodule to this repo.

**Comment by revilowaldow** [comment]
I think having them dynamically linked is greatly preferable to having to do commits every time there's an update. A sub module may be a good shout, though if AJV add url support that would be much simpler to implement.

**Comment by revilowaldow** [comment]
https://ajv.js.org/guide/managing-schemas.html#asynchronous-schema-compilation

```js
const validate = ajv.getSchema("https://example.com/user.json")|| ajv.compile(schema_user)
```

**Comment by MrVauxs** [comment]
> though if AJV add url support that would be much simpler to implement

Unfortunately this simple thing is beyond me 😅

**Comment by revilowaldow** [comment]
This can probably be closed :woozy_pinching_coffee:
