### ISSUE TITLE
Dinner at Lionlodge

### ISSUE THREAD

**Issue by CnrDmr** [Pf2eTools/homebrew#5]
I'm preparing to run this one shot but some of the items/creatures in the adventure are not present on the website. I took screenshots to make them easy to reference but obviously this way (or even using the PDF) I lose the "hover for details" function of the website which is super useful when you're beginner-ish. I'm also applying a Weak adjustment to the boss but there's no way to do it on the PDF.

Can someone add:
- Cultist of Alocer (creature lvl3) [different from the lvl1 Cultist upscaled to lvl3]
- Simulacra (creature lvl4)
- Poisoned Lock (hazard lvl5) [different from the lvl1 one found in the CRB]
- Spider Mold (item lvl4)

to a homebrew file or the website. I would be super grateful.

**Comment by MrVauxs** [comment]
It's an open issue on the official repo, it'll get converted eventually: https://github.com/Pf2eToolsOrg/Pf2eTools/issues/276
